class ProductAccessoriseList{
  final String? imagAcc,nameAcc,subtitalAcc;
  final double? priceAcc;


  ProductAccessoriseList(
      {this.imagAcc, this.nameAcc, this.subtitalAcc, this.priceAcc});
static List<ProductAccessoriseList>productAccessoriseList=[

  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_1.png",nameAcc: "Sliver RING",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery.png",nameAcc: "GOLD NECKLACES",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_2.png",nameAcc: "Sliver BRACELETS",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_2.png",nameAcc: "GOLD NECKLACES",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_3.png",nameAcc: "GOLD BRACELETS",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_3.png",nameAcc: "Sliver Ring",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_4.png",nameAcc: "Sliver Ring",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_4.png",nameAcc: "GOLD NECKLACES",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_5.png",nameAcc: "GOLD BRACELETS",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_5.png",nameAcc: "GOLD NECKLACES",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_6.png",nameAcc: "GOLD BRACELETS",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_6.png",nameAcc: "Sliver Ring",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_7.png",nameAcc: "Sliver Ring",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_7.png",nameAcc: "Sliver Ring",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_8.png",nameAcc: "Sliver Ring",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_8.png",nameAcc: "Sliver Ring",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_9.png",nameAcc: "Sliver Ring",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_9.png",nameAcc: "Gold EARRINGS",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/ring_10.png",nameAcc: "GOLD BRACELETS",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_10.png",nameAcc: "Gold EARRINGS",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_11.png",nameAcc: "Sliver NECKLACES",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_12.png",nameAcc: "Sliver NECKLACES",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
  ProductAccessoriseList(imagAcc: "assets/images/accessories/jwellery_13.png",nameAcc: "Sliver EARRINGS",subtitalAcc: "From everyday jewellery essentials in delicate silver and gold-plated to dazzling hero pieces that make a fashionable statement, discover uplifting jewellery to bring that little extra sparkle to your outfit. Brighten your look with our uniquely-designed earrings and studs, opt for the latest trends in layering necklaces, all-rounder bracelets and bangles, and complete your jewellery set with plenty of eye-catching, mixed-and-matched rings.",priceAcc: 422.9),
];
}